# Generated by Django 2.2 on 2019-12-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_sponsorshiplevel_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipperiod',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Bill customer at the start of each period'),
        ),
        migrations.AlterField(
            model_name='sponsorshipperiod',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of sponsorship period', null=True, verbose_name='End date'),
        ),
    ]
