# Generated by Django 2.2 on 2019-12-19 07:11

import changes.models.sponsor
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0005_sponsorshipperiod_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sustaining_membership',
            field=models.BooleanField(default=False, verbose_name='Check if this data is sustaining membership'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='address',
            field=models.TextField(blank=True, help_text="Provide your / your organisation's complete address. Use line breaks...", null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Input the contact person.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Title of the representative i.e Treasurer.', max_length=255, null=True, verbose_name='Representative Title'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Select the country.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(help_text='An image of your / your organisation logo e.g. a splashscreen. Most browsers support dragging the image directly on to the "Choose File" button above.', upload_to='images/projects'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(help_text='Name of organisation or individual.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_email',
            field=models.CharField(blank=True, help_text='Enter the email of the contact person.', max_length=255, null=True, validators=[changes.models.sponsor.validate_email_address], verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_url',
            field=models.CharField(blank=True, help_text='Website for the organisation or individual.', max_length=255, null=True, verbose_name='Organisation URL'),
        ),
    ]
