# Generated by Django 2.2 on 2020-03-11 11:21

import changes.utils.custom_slugfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0008_auto_20200129_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='slug',
            field=changes.utils.custom_slugfield.CustomSlugField(),
        ),
    ]
