# Generated by Django 2.2 on 2020-07-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0010_version_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='github_PR_url',
            field=models.CharField(blank=True, help_text='Input the Github PR URL when applicable.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='locked',
            field=models.BooleanField(default=False, help_text='Whether this version is locked for editing.'),
        ),
    ]
