language: python

services:
  - postgresql

env:
  global:
    - ON_TRAVIS=true
    - DATABASE_URL='postgres://postgres:@localhost:5432/test_db'
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DJANGO_SETTINGS_MODULE=core.settings.test_travis

sudo: false
dist: trusty

python:
  - '2.7'

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-9.3-postgis-2.3

install:
  - pip install coveralls
  - pip install -r REQUIREMENTS-dev.txt


before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db

script:
  - flake8 --config .flake8 django_project
  - cd django_project
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test core base certification

after_success:
  - coveralls

email:
 - tim@kartoza.com
 - rischan@kartoza.com
