# Generated by Django 2.2 on 2019-12-04 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifyingorganisationcertificate',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 5, 15, 14, 131955)),
        ),
        migrations.AlterField(
            model_name='historicalcertifyingorganisationcertificate',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 5, 15, 14, 131955)),
        ),
    ]
