# Generated by Django 2.2 on 2019-12-04 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_auto_20191204_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifyingorganisationcertificate',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalcertifyingorganisationcertificate',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
