# Generated by Django 2.2.13 on 2021-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_auto_20200724_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='slug',
            field=models.SlugField(),
        ),
    ]
