# Generated by Django 2.2.18 on 2021-12-10 02:23

from django.db import migrations, models
import django.db.models.deletion

def create_existing_project_certificate_type(apps, schema_editor):
    CertificateType = apps.get_model('certification', 'CertificateType')
    ProjectCertificateType = apps.get_model('certification', 'ProjectCertificateType')
    Project = apps.get_model('base', 'Project')
    certificate_type = CertificateType.objects.filter(
        name='attendance and completion').first()
    projects = Project.objects.all()

    for project in projects:
        ProjectCertificateType.objects.create(
            project=project,
            certificate_type=certificate_type
        )

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210308_0244'),
        ('certification', '0007_certificatetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.CertificateType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project')),
            ],
        ),

        migrations.RunPython(create_existing_project_certificate_type, reverse_code=migrations.RunPython.noop),
    ]
