# Generated by Django 2.2.18 on 2022-02-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210308_0244'),
        ('certification', '0009_course_certificate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question for certifying organisation applicant.', max_length=1000, unique=True)),
                ('sort_number', models.SmallIntegerField(blank=True, help_text='The order in which this category is listed within a project', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Is this question archived?')),
                ('is_additional_response_enabled', models.BooleanField(default=False, help_text='Let the applicant add a response when making their application.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project')),
            ],
            options={
                'unique_together': {('question', 'sort_number')},
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certification.CertificateType'),
        ),
        migrations.CreateModel(
            name='CertifyingOrganisationChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(help_text='Is the answer is yes or no', null=True)),
                ('certifying_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.CertifyingOrganisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.CertificateChecklist')),
            ],
            options={
                'unique_together': {('question', 'certifying_organisation')},
            },
        ),
    ]
