# Generated by Django 2.2.18 on 2022-02-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_courseconvener_is_active'),
        ('certification', '0009_course_certificate_type'),
    ]

    operations = [
    ]
