# Generated by Django 2.2.18 on 2022-02-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0010_auto_20220204_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifyingorganisationchecklist',
            name='applicant_response',
            field=models.CharField(blank=True, help_text='Response from applicant.', max_length=1000, null=True),
        ),
    ]
