# Generated by Django 2.2.18 on 2022-02-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0011_certifyingorganisationchecklist_applicant_response'),
        ('certification', '0010_merge_20220212_0417'),
    ]

    operations = [
    ]
