# Generated by Django 3.2.13 on 2022-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0018_externalreviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcertifyingorganisation',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertifyingorganisationcertificate',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalchecklist',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
