# Generated by Django 3.2.13 on 2022-04-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0019_auto_20220420_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationchecklist',
            name='external_submitter',
            field=models.ForeignKey(blank=True, help_text='External reviewer who submitted the checklist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_external_submitter', to='certification.externalreviewer'),
        ),
    ]
