# Generated by Django 3.2.13 on 2022-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0020_organisationchecklist_external_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='help_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklist',
            name='help_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
