# Generated by Django 3.2.13 on 2022-04-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0021_auto_20220422_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreviewer',
            name='name',
            field=models.CharField(blank=True, help_text='External reviewer name', max_length=512, null=True),
        ),
    ]
