# Generated by Django 3.2.13 on 2022-06-05 04:12

from django.db import migrations


def set_issue_date_to_null(apps, schema_editor):
    Ceritificate = apps.get_model('certification', 'Certificate')
    Ceritificate.objects.all().update(issue_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0023_certificate_issue_date'),
    ]

    operations = [
        migrations.RunPython(set_issue_date_to_null)
    ]
