# Generated by Django 3.2.13 on 2025-01-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0025_alter_attendee_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifyingorganisation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is this organisation archived?'),
        ),
        migrations.AddField(
            model_name='historicalcertifyingorganisation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is this organisation archived?'),
        ),
    ]
