# Generated by Django 3.2.13 on 2025-01-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0025_alter_attendee_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certification.certificatetype'),
        ),
    ]
