# Generated by Django 2.0.3 on 2018-03-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextServiceRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Context Service.', max_length=200)),
                ('display_name', models.CharField(help_text='Display Name of Context Service.', max_length=200)),
                ('description', models.CharField(help_text='Description of Context Service.', max_length=1000)),
                ('url', models.CharField(help_text='URL of Context Service.', max_length=1000)),
                ('user', models.CharField(blank=True, help_text='User name for accessing Context Service.', max_length=200)),
                ('password', models.CharField(blank=True, help_text='Password for accessing Context Service.', max_length=200)),
                ('api_key', models.CharField(blank=True, help_text='API key for accessing Context Service.', max_length=200)),
                ('query_url', models.CharField(help_text='Query URL for accessing Context Service.', max_length=1000)),
                ('query_type', models.CharField(blank=True, choices=[('wfs', 'WFS'), ('wcs', 'WCS'), ('wms', 'WMS'), ('rest', 'REST'), ('wikipedia', 'Wikipedia')], help_text='Query type of the Context Service.', max_length=200)),
                ('result_regex', models.CharField(blank=True, help_text='Regex to retrieve the desired value.', max_length=200)),
                ('time_to_live', models.IntegerField(blank=True, help_text='Time to live of Context Service to be used in caching.')),
            ],
        ),
    ]
