# Generated by Django 2.0.3 on 2018-03-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='time_to_live',
            field=models.IntegerField(blank=True, help_text='Time to live of Context Service to be used in caching.', null=True),
        ),
    ]
