# Generated by Django 2.0.3 on 2018-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0002_auto_20180328_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextserviceregistry',
            name='crs',
            field=models.IntegerField(blank=True, default=4326, help_text='The CRS of the context service registry in EPSG code.', null=True),
        ),
    ]
