# Generated by Django 2.0.3 on 2018-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0003_contextserviceregistry_crs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextserviceregistry',
            name='layer_typename',
            field=models.CharField(default='', help_text='Layer type name to get the context.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contextserviceregistry',
            name='service_version',
            field=models.CharField(default='1.0.0', help_text='Version of the service (e.g. WMS 1.1.0, WFS 2.0.0).', max_length=200),
            preserve_default=False,
        ),
    ]
