# Generated by Django 2.0.3 on 2018-04-09 04:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0004_auto_20180406_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Cache Context.', max_length=200)),
                ('source_uri', models.CharField(help_text='Source URI of the Context.', max_length=200)),
                ('geometry_line', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='The line geometry of the context.', null=True, srid=4326)),
                ('geometry_multi_line', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, help_text='The multi line geometry of the field.', null=True, srid=4326)),
                ('geometry_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='The polygon geometry of the context.', null=True, srid=4326)),
                ('geometry_multi_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The multi polygon geometry of the field.', null=True, srid=4326)),
                ('value', models.CharField(help_text='The value of the context.', max_length=200)),
                ('expired_time', models.DateTimeField(help_text='When the cache expired.')),
                ('service_registry', models.ForeignKey(help_text='Service registry where the context comes from', on_delete=django.db.models.deletion.CASCADE, to='geocontext.ContextServiceRegistry')),
            ],
        ),
    ]
