# Generated by Django 2.0.3 on 2018-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0005_contextcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextcache',
            name='source_uri',
            field=models.CharField(help_text='Source URI of the Context.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='time_to_live',
            field=models.IntegerField(blank=True, default=604800, help_text='Time to live of Context Service to be used in caching in seconds unit.', null=True),
        ),
    ]
