# Generated by Django 2.0.3 on 2018-04-09 05:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0006_auto_20180409_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, help_text='The line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_multi_line',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=3, help_text='The multi line geometry of the field.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_multi_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, help_text='The multi polygon geometry of the field.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, help_text='The polygon geometry of the context.', null=True, srid=4326),
        ),
    ]
