# Generated by Django 2.0.3 on 2018-04-09 05:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0007_auto_20180409_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextcache',
            name='geometry_line',
        ),
        migrations.RemoveField(
            model_name='contextcache',
            name='geometry_multi_line',
        ),
        migrations.RemoveField(
            model_name='contextcache',
            name='geometry_multi_polygon',
        ),
        migrations.RemoveField(
            model_name='contextcache',
            name='geometry_polygon',
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='The 2D geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_3d',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=3, help_text='The 3D geometry of the context.', null=True, srid=4326),
        ),
    ]
