# Generated by Django 2.0.3 on 2018-04-11 03:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0009_auto_20180409_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextcache',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='contextcache',
            name='geometry_3d',
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_linestring',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, help_text='The line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_multi_linestring',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=3, help_text='The multi line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_multi_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, help_text='The multi polygon geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, help_text='The polygon geometry of the context.', null=True, srid=4326),
        ),
    ]
