# Generated by Django 2.0.3 on 2018-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0010_auto_20180411_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextserviceregistry',
            name='crs',
        ),
        migrations.AddField(
            model_name='contextserviceregistry',
            name='srid',
            field=models.IntegerField(blank=True, default=4326, help_text='The Spatial Reference ID of the service registry.', null=True),
        ),
    ]
