# Generated by Django 2.0.3 on 2018-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0011_auto_20180411_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for accessing Context Service.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='description',
            field=models.CharField(blank=True, help_text='Description of Context Service.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='password',
            field=models.CharField(blank=True, help_text='Password for accessing Context Service.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='query_type',
            field=models.CharField(choices=[('wfs', 'WFS'), ('wcs', 'WCS'), ('wms', 'WMS'), ('rest', 'REST'), ('wikipedia', 'Wikipedia')], help_text='Query type of the Context Service.', max_length=200),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='result_regex',
            field=models.CharField(help_text='Regex to retrieve the desired value.', max_length=200),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='user',
            field=models.CharField(blank=True, help_text='User name for accessing Context Service.', max_length=200, null=True),
        ),
    ]
