# Generated by Django 2.0.3 on 2018-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0012_auto_20180411_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='name',
            field=models.CharField(help_text='Name of Context Service.', max_length=200, unique=True),
        ),
    ]
