# Generated by Django 2.0.3 on 2018-04-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0013_auto_20180411_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='query_type',
            field=models.CharField(choices=[('WFS', 'WFS'), ('WCS', 'WCS'), ('WMS', 'WMS'), ('REST', 'REST'), ('Wikipedia', 'Wikipedia')], help_text='Query type of the Context Service.', max_length=200),
        ),
    ]
