# Generated by Django 2.0.2 on 2018-03-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20180312_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdocument',
            options={'verbose_name': 'CSV Document', 'verbose_name_plural': 'CSV Documents'},
        ),
        migrations.AlterModelOptions(
            name='iucnstatus',
            options={'verbose_name': 'IUCN Status', 'verbose_name_plural': 'IUCN Status'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name': 'Taxon', 'verbose_name_plural': 'Taxa'},
        ),
        migrations.AlterField(
            model_name='fishcollectionrecord',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='iucn_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IUCNStatus'),
        ),
    ]
