# Generated by Django 2.0.2 on 2018-03-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_auto_20180312_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='gbif_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='GBIF id'),
        ),
        migrations.AlterField(
            model_name='fishcollectionrecord',
            name='taxon_gbif_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.Taxon', verbose_name='Taxon GBIF '),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='iucn_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IUCNStatus'),
        ),
    ]
