# Generated by Django 2.0.2 on 2018-03-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_auto_20180312_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='iucnstatus',
            name='narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='iucn_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish.IUCNStatus'),
        ),
    ]
