# Generated by Django 2.2 on 2020-01-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credit_cost_currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€')], help_text='Currency for cost of credits', max_length=10, null=True),
        ),
    ]
