# Generated by Django 2.2 on 2020-03-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('base', '0004_auto_20200110_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFlatpage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
