# Generated by Django 2.2.13 on 2021-03-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_projectflatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_certification',
            field=models.BooleanField(default=True, help_text='Whether this Project has Certification.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_changelogs',
            field=models.BooleanField(default=True, help_text='Whether this Project has Changelogs.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_lessons',
            field=models.BooleanField(default=True, help_text='Whether this Project has Lessons.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_sustaining_members',
            field=models.BooleanField(default=True, help_text='Whether this Project has Sustaining Members.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_teams',
            field=models.BooleanField(default=True, help_text='Whether this Project has Teams.'),
        ),
    ]
