# Generated by Django 3.2.13 on 2022-04-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210308_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_reviewer_invitation',
            field=models.TextField(blank=True, default='You have been invited to review this organisation.', help_text='Standard text for external reviewer of what they are expected to do.', max_length=10000, null=True),
        ),
    ]
