# Generated by Django 2.2.13 on 2021-01-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True, help_text='Time stamp when the last worksheet updated.', null=True)),
                ('last_update_en', models.DateTimeField(blank=True, help_text='Time stamp when the last worksheet updated.', null=True)),
                ('last_update_ind', models.DateTimeField(blank=True, help_text='Time stamp when the last worksheet updated.', null=True)),
                ('name', models.CharField(help_text='Name of license.', max_length=200)),
                ('description', models.TextField(help_text='Describe the license.')),
                ('description_en', models.TextField(help_text='Describe the license.', null=True)),
                ('description_ind', models.TextField(help_text='Describe the license.', null=True)),
                ('url', models.URLField(help_text='Input the license URL.')),
                ('file', models.FileField(help_text='License content in the text format. Usually a txt file. Most browsers support dragging the file directly on to the "Choose File" button above.', upload_to='images/lesson/license')),
            ],
        ),
        migrations.AddField(
            model_name='worksheet',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.License'),
        ),
    ]
