# Generated by Django 2.2.13 on 2021-01-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210104_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='exercise_image_dimension',
            field=models.CharField(blank=True, help_text='Set the height and width of exercise_image element in a css format. e.g <b>height: 200px; width: 300px;</b>. The value will be embedded on image style attribute in the PDF output.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='more_about_image_dimension',
            field=models.CharField(blank=True, help_text='Set the height and width of more_about_image element in a css format. e.g <b>height: 200px; width: 300px;</b>. The value will be embedded on image style attribute in the PDF output.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='summary_image_dimension',
            field=models.CharField(blank=True, help_text='Set the height and width of summary_image element in a css format. e.g <b>height: 200px; width: 300px;</b>. The value will be embedded on image style attribute in the PDF output.', max_length=200, null=True),
        ),
    ]
