# Generated by Django 2.2.13 on 2021-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210104_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='funded_by',
            field=models.CharField(blank=True, help_text='Input the funder name.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='funder_url',
            field=models.CharField(blank=True, help_text='Input the funder URL.', max_length=255, null=True),
        ),
    ]
