# Generated by Django 2.2.13 on 2021-01-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210104_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='description',
            field=models.CharField(blank=True, help_text='Description of value field. Markdown is supported', max_length=200),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='requirement_header_name_first',
            field=models.CharField(blank=True, help_text='Set header name of the first column in requirements table questions.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='requirement_header_name_last',
            field=models.CharField(blank=True, help_text='Set header name of the last column in requirements table questions.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='notes',
            field=models.CharField(blank=True, help_text='Description of title field. Markdown is supported', max_length=200),
        ),
        migrations.AlterField(
            model_name='specification',
            name='notes_en',
            field=models.CharField(blank=True, help_text='Description of title field. Markdown is supported', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='notes_ind',
            field=models.CharField(blank=True, help_text='Description of title field. Markdown is supported', max_length=200, null=True),
        ),
    ]
