# Generated by Django 2.2.13 on 2021-01-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20210108_1046'),
        ('lesson', '0003_auto_20210111_0338'),
    ]

    operations = [
    ]
