# Generated by Django 2.2.13 on 2021-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20210111_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='notes',
            new_name='title_notes',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='notes_en',
            new_name='title_notes_en',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='notes_ind',
            new_name='title_notes_ind',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='description',
            new_name='value_notes',
        ),
        migrations.AddField(
            model_name='specification',
            name='value_notes_en',
            field=models.CharField(blank=True, help_text='Description of value field. Markdown is supported', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='value_notes_ind',
            field=models.CharField(blank=True, help_text='Description of value field. Markdown is supported', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='requirement_header_name_first',
            field=models.CharField(blank=True, help_text='Set header name of the first column in requirements table questions. Markdown is supported.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='requirement_header_name_last',
            field=models.CharField(blank=True, help_text='Set header name of the last column in requirements table questions. Markdown is supported.', max_length=200, null=True),
        ),
    ]
