# Generated by Django 2.2.13 on 2021-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20210111_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='title_notes',
            field=models.CharField(blank=True, help_text='Description of title field. Markdown is supported', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value_notes',
            field=models.CharField(blank=True, help_text='Description of value field. Markdown is supported', max_length=200, null=True),
        ),
    ]
