# Generated by Django 2.2.13 on 2021-01-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_merge_20210112_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='exercise_image_dimension',
            field=models.CharField(blank=True, help_text='Set the height and width of exercise_image element in a css format. e.g <b>height: 200px; width: 300px;</b>. The value will be added onto image style attribute in the PDF output.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='more_about_image_dimension',
            field=models.CharField(blank=True, help_text='Set the height and width of more_about_image element in a css format. e.g <b>height: 200px; width: 300px;</b>. The value will be added onto image style attribute in the PDF output.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='summary_image_dimension',
            field=models.CharField(blank=True, help_text='Set the height and width of summary_image element in a css format. e.g <b>height: 200px; width: 300px;</b>. The value will be added onto image style attribute in the PDF output.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='summary_text',
            field=models.TextField(help_text='Content of the Summary. Markdown is supported. Add the following text to insert a page break in the PDF output: a &ltdiv class="page-break"&gt&lt/div&gt element between sections of the content.'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='summary_text_en',
            field=models.TextField(help_text='Content of the Summary. Markdown is supported. Add the following text to insert a page break in the PDF output: a &ltdiv class="page-break"&gt&lt/div&gt element between sections of the content.', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='summary_text_ind',
            field=models.TextField(help_text='Content of the Summary. Markdown is supported. Add the following text to insert a page break in the PDF output: a &ltdiv class="page-break"&gt&lt/div&gt element between sections of the content.', null=True),
        ),
    ]
