# Generated by Django 2.2.13 on 2021-01-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20210112_0617'),
        ('lesson', '0005_auto_20210112_0907'),
    ]

    operations = [
    ]
