# Generated by Django 2.2.13 on 2021-01-14 07:47

from django.db import migrations, models


def set_published_true(apps, schema_editor):
    Worksheet = apps.get_model("lesson", "Worksheet")
    old_data = Worksheet.objects.all()
    for data in old_data:
        data.published = True
        data.save(update_fields=['published'])


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_merge_20210112_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether this worksheet is visible for public.'),
        ),

        # Run custom function
        migrations.RunPython(set_published_true),
    ]
