# Generated by Django 2.2.13 on 2021-01-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_merge_link_furtherreading'),
        ('lesson', '0007_worksheet_published'),
    ]

    operations = [
    ]
