# Generated by Django 2.2.13 on 2021-02-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_merge_20210118_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_exercise',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the Exercise content.'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_exercise_image',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the Exercise image.'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_further_reading',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the Further Reading content.'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_more_about',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the More About content.'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_question',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the Question content.'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_requirement_table',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the Requirement table.'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='page_break_before_youtube_link',
            field=models.BooleanField(default=False, help_text='Check if you wish a page break before the YouTube Link.'),
        ),
    ]
