name: stable-build
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  docker-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/docker/Dockerfile
          push: true
          target: prod
          tags: ${{ secrets.DOCKERHUB_REPO }}/projecta-uwsgi:stable
          cache-from: type=gha,scope=prod
          cache-to: type=gha,scope=prod
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
